[package]
name = "smq_game"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]
name = "smq_game_lib"
path = "src/main.rs"

[dependencies]
smq_engine = { path = "../engine" }

winit = "0.30.0"
glam = { version = "0.33.6", features = ["bytemuck"] }
wgpu = { version = "30.0", default-features = false, features = ["webgpu", "vulkan"] }
image = { version = "0.25.10", default-features = false, features = ["png"] }
bytemuck = { version = "1.25", features = ["derive"] }
log = "0.4"
egui = { version = "0.36" }
egui-winit = { version = "0.36", default-features = false, features = ["links"]}
egui-wgpu = { version = "0.36" }
bevy_ecs = "0.19"
web-time = "1.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"
web-sys = { version = "0.3", features = ["Document", "Window", "Element", "HtmlCanvasElement", "Node"] }
wasm-bindgen-futures = "0.4"

[package.metadata.wasm-pack.profile.release]
wasm-opt = [
    "-O4", 
    "--enable-bulk-memory", 
    "--enable-nontrapping-float-to-int"
]