#pragma once
#include <Smq.h>

// This code is generated by SAM.

void initSam();
void quitSam();

enum Meshes : unsigned int {
	m_ball,
	m_plane,
};

smq::Mesh* GetMesh(Meshes mesh);

enum Textures : unsigned int {
	t_non,
};

smq::Texture* GetTexture(Textures texture);

enum Materials : unsigned int {
	s_basic,
	s_post,
	s_shadow,
};

enum MaterialUniforms : unsigned int {
	s_basic_vs_u_mvp = 0,
	s_basic_vs_u_normal_mvp = 1,
	s_basic_vs_u_model = 2,
	s_basic_fs_u_tex = 3,
	s_post_fs_u_tex = 0,
	s_post_fs_u_depth = 1,
	s_shadow_vs_u_mvp = 0,
	s_shadow_vs_u_normal_mvp = 1,
	s_shadow_vs_u_model = 2,
	s_shadow_vs_u_lightSpaceMatrix = 3,
	s_shadow_fs_u_tex = 4,
	s_shadow_fs_u_shadowMap = 5,
	s_shadow_fs_u_lightCount = 6,
};

smq::Material* GetMaterial(Materials material);
