[workspace]
members = [
    "engine",
    "editor",
    "game"
]
resolver = "2"

# Globalne profile kompilacji dla całego projektu!
[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

[workspace.metadata.wasm-pack.profile.dev]
wasm-opt = false

[workspace.metadata.wasm-pack.profile.release]
wasm-opt = [
    "-O4", 
    "--enable-bulk-memory", 
    "--enable-nontrapping-float-to-int"
]