// this code is generated by code
// if you change this file your changes will be deleted

#![allow(non_snake_case, unused)]

use glam::*;
use smq_engine::*;
use wgpu::*;

#[repr(C)]
#[derive(Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct RendererUbodata0Ubo {
    pub proj: Mat4,
}

impl Default for RendererUbodata0Ubo {
    fn default() -> Self {
        Self {
            proj: Mat4::IDENTITY,
        }
    }
}

#[repr(C)]
#[derive(Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct RendererUbodata1Ubo {
    pub view: Mat4,
}

impl Default for RendererUbodata1Ubo {
    fn default() -> Self {
        Self {
            view: Mat4::IDENTITY,
        }
    }
}

#[repr(C)]
#[derive(Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct RendererUbodata2Ubo {
    pub model: Mat4,
}

impl Default for RendererUbodata2Ubo {
    fn default() -> Self {
        Self {
            model: Mat4::IDENTITY,
        }
    }
}

pub struct GenAssets {
    pub renderer_main_renderTexture: RenderTexture,
    pub renderer_ubodata0_ubo: Ubo<RendererUbodata0Ubo>,
    pub renderer_ubodata1_ubo: Ubo<RendererUbodata1Ubo>,
    pub renderer_ubodata2_ubo: Ubo<RendererUbodata2Ubo>,
}

impl GenAssets {
    pub fn init_gen_assets(context: &Context) -> Self {
        let renderer_main_renderTexture = RenderTexture::new(
            context,
            1280,
            720,
            &[(
                TextureFormat::Rgba8Unorm,
                TextureUsages::RENDER_ATTACHMENT
                    | TextureUsages::TEXTURE_BINDING
                    | TextureUsages::empty(),
                Some("renderer_main_renderTexture_0"),
            )],
            Some((
                TextureFormat::Depth32Float,
                TextureUsages::RENDER_ATTACHMENT | TextureUsages::empty(),
                Some("renderer_main_renderTexture_depth"),
            )),
        );
        let mut renderer_ubodata0_ubo = Ubo::new(context, RendererUbodata0Ubo::default());
        let mut renderer_ubodata1_ubo = Ubo::new(context, RendererUbodata1Ubo::default());
        let mut renderer_ubodata2_ubo = Ubo::new(context, RendererUbodata2Ubo::default());

        return Self {
            renderer_main_renderTexture,
            renderer_ubodata0_ubo,
            renderer_ubodata1_ubo,
            renderer_ubodata2_ubo,
        };
    }
}
