// this code is generated by code
// if you change this file your changes will be deleted

#![allow(non_snake_case, unused, non_camel_case_types)]

use glam::*;
use smq_engine::*;
use wgpu::*;

#[repr(usize)]
#[derive(Clone, Copy)]
pub enum Meshes {
    file_mesh_Cart_smf = 0,
    file_mesh_Cube_smf = 1,
    file_mesh_Floor_smf = 2,
    file_mesh_Walls_smf = 3,
}

#[repr(C)]
#[derive(Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct UcLight {
    pub position: Vec3,
    pub _pad0: [u8; 4],
    pub color: Vec3,
    pub power: f32,
}

impl Default for UcLight {
    fn default() -> Self {
        Self {
            position: Vec3::ZERO,
            _pad0: [0; 4],
            color: Vec3::ZERO,
            power: 0.0,
        }
    }
}

#[repr(C)]
#[derive(Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct UboDefferedInfo {
    pub camera_position: Vec3,
    pub light_count: u32,
    pub lights: [UcLight; 16],
    pub instance_count: u32,
    pub _pad0: [u8; 12],
}

impl Default for UboDefferedInfo {
    fn default() -> Self {
        Self {
            camera_position: Vec3::ZERO,
            light_count: 0,
            lights: Default::default(),
            instance_count: 0,
            _pad0: [0; 12],
        }
    }
}

#[repr(C)]
#[derive(Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct UboData0 {
    pub proj: Mat4,
}

impl Default for UboData0 {
    fn default() -> Self {
        Self {
            proj: Mat4::IDENTITY,
        }
    }
}

#[repr(C)]
#[derive(Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct UboData1 {
    pub view: Mat4,
}

impl Default for UboData1 {
    fn default() -> Self {
        Self {
            view: Mat4::IDENTITY,
        }
    }
}

#[repr(C)]
#[derive(Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct DUboData2 {
    pub model: Mat4,
    pub _pad0: [u8; 192],
}

impl Default for DUboData2 {
    fn default() -> Self {
        Self {
            model: Mat4::IDENTITY,
            _pad0: [0; 192],
        }
    }
}

pub struct GenAssets {
    pub ubodefferedinfo: Ubo<UboDefferedInfo>,
    pub ubodata0: Ubo<UboData0>,
    pub ubodata1: Ubo<UboData1>,
    pub dubodata2: DynamicUbo<DUboData2>,
    pub lakaka_png: TextureS,
    pub renderer_main_renderTexture: RenderTexture,
    pub renderer_post_renderTexture: RenderTexture,
    pub blitinfo: BlitInfo,
    pub blit_group: BindGroupS,
    pub meshes: [Mesh; 4],
}

impl GenAssets {
    pub fn init_gen_assets<D>(context: &Context<D>, ssf_data: &[SSFAsset]) -> Self {
        let meshes = [
            Mesh::new(
                context,
                ssf_data[1].as_ref(),
                32,
                Some("file_mesh_Cart_smf"),
            )
            .unwrap(),
            Mesh::new(
                context,
                ssf_data[2].as_ref(),
                32,
                Some("file_mesh_Cube_smf"),
            )
            .unwrap(),
            Mesh::new(
                context,
                ssf_data[3].as_ref(),
                32,
                Some("file_mesh_Floor_smf"),
            )
            .unwrap(),
            Mesh::new(
                context,
                ssf_data[4].as_ref(),
                32,
                Some("file_mesh_Walls_smf"),
            )
            .unwrap(),
        ];

        let mut ubodefferedinfo = Ubo::new(context, UboDefferedInfo::default());
        let mut ubodata0 = Ubo::new(context, UboData0::default());
        let mut ubodata1 = Ubo::new(context, UboData1::default());
        let mut dubodata2 = DynamicUbo::new(
            context,
            std::iter::repeat_with(DUboData2::default)
                .take(1024)
                .collect(),
        );
        let lakaka_png = TextureS::new(
            context,
            ssf_data[0].as_ref(),
            smq_engine::SamplingMode::NearestMapped,
            4,
            TextureFormat::Rgba8UnormSrgb,
            AddressMode::Repeat,
            Some("lakaka_png"),
        );
        let renderer_main_renderTexture = RenderTexture::new(
            context,
            384,
            216,
            &[
                (
                    TextureFormat::Rgba8Unorm,
                    TextureUsages::RENDER_ATTACHMENT
                        | TextureUsages::TEXTURE_BINDING
                        | TextureUsages::empty(),
                    Some("renderer_main_renderTexture_0"),
                ),
                (
                    TextureFormat::Rgba32Float,
                    TextureUsages::RENDER_ATTACHMENT
                        | TextureUsages::TEXTURE_BINDING
                        | TextureUsages::empty(),
                    Some("renderer_main_renderTexture_1"),
                ),
                (
                    TextureFormat::Rgba16Float,
                    TextureUsages::RENDER_ATTACHMENT
                        | TextureUsages::TEXTURE_BINDING
                        | TextureUsages::empty(),
                    Some("renderer_main_renderTexture_2"),
                ),
            ],
            Some((
                TextureFormat::Depth32Float,
                TextureUsages::RENDER_ATTACHMENT | TextureUsages::empty(),
                Some("renderer_main_renderTexture_depth"),
            )),
        );
        let renderer_post_renderTexture = RenderTexture::new(
            context,
            384,
            216,
            &[(
                TextureFormat::Rgba8Unorm,
                TextureUsages::RENDER_ATTACHMENT
                    | TextureUsages::TEXTURE_BINDING
                    | TextureUsages::empty(),
                Some("renderer_post_renderTexture_0"),
            )],
            None,
        );

        let blit_group = BindGroupS::new(
            context,
            &[
                renderer_post_renderTexture.attachments[0]
                    .get_texture_binding(ShaderStages::FRAGMENT, true),
                renderer_post_renderTexture.attachments[0]
                    .get_sampler_binding(ShaderStages::FRAGMENT),
            ],
            None,
        );

        let blitinfo = context.create_blit_pipeline(&blit_group);

        return Self {
            ubodefferedinfo,
            ubodata0,
            ubodata1,
            dubodata2,
            lakaka_png,
            renderer_main_renderTexture,
            renderer_post_renderTexture,
            blitinfo,
            blit_group,
            meshes,
        };
    }
}
