
// this code is generated by code
// if you change this file your changes will be deleted

#[repr(usize)]
enum game {
    file_tit_png = 0,
    file_Untitled_Suzanne_smf = 1,
    file_basic_wgsl = 2,
}