// this code is generated by code
// if you change this file your changes will be deleted

#![allow(non_snake_case, unused)]

use glam::*;
use smq_engine::*;
use wgpu::*;

#[repr(C)]
#[derive(Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct UboData0 {
    pub proj: Mat4,
}

impl Default for UboData0 {
    fn default() -> Self {
        Self {
            proj: Mat4::IDENTITY,
        }
    }
}

#[repr(C)]
#[derive(Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct UboData1 {
    pub view: Mat4,
}

impl Default for UboData1 {
    fn default() -> Self {
        Self {
            view: Mat4::IDENTITY,
        }
    }
}

#[repr(C)]
#[derive(Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
pub struct UboData2 {
    pub model: Mat4,
}

impl Default for UboData2 {
    fn default() -> Self {
        Self {
            model: Mat4::IDENTITY,
        }
    }
}

pub struct GenAssets {
    pub ubodata0: Ubo<UboData0>,
    pub ubodata1: Ubo<UboData1>,
    pub ubodata2: Ubo<UboData2>,
    pub renderer_main_renderTexture: RenderTexture,
}

impl GenAssets {
    pub fn init_gen_assets(context: &Context) -> Self {
        let mut ubodata0 = Ubo::new(context, UboData0::default());
        let mut ubodata1 = Ubo::new(context, UboData1::default());
        let mut ubodata2 = Ubo::new(context, UboData2::default());
        let renderer_main_renderTexture = RenderTexture::new(
            context,
            7680,
            4320,
            &[(
                TextureFormat::Rgba8Unorm,
                TextureUsages::RENDER_ATTACHMENT
                    | TextureUsages::TEXTURE_BINDING
                    | TextureUsages::empty(),
                Some("renderer_main_renderTexture_0"),
            )],
            Some((
                TextureFormat::Depth32Float,
                TextureUsages::RENDER_ATTACHMENT | TextureUsages::empty(),
                Some("renderer_main_renderTexture_depth"),
            )),
        );

        return Self {
            ubodata0,
            ubodata1,
            ubodata2,
            renderer_main_renderTexture,
        };
    }
}
