use std::{fs, path::PathBuf};
use std::io::{Error, ErrorKind};

pub enum SSFAsset {
    Binary(Vec<u8>)
}

#[allow(unused)]
pub fn save_autodir_ssf(file_name: &str, folder: PathBuf) {
    todo!();
}

pub fn save_custom_ssf(file_name: &str, files: Vec<(PathBuf, String, u8)>) {
    let mut out: Vec<u8> = Vec::new();
    out.extend_from_slice(b"SMF");
    
    let mut code = format!("
// this code is generated by code
// if you change this file your changes will be deleted

#[repr(usize)]
enum {file_name} {{
");

    for (i, (path, name, id)) in files.iter().enumerate() {
        let data = fs::read(path).unwrap_or_else(|_| panic!("failed to open {}", path.display()));

        out.push(*id);

        let datalen = (data.len() as u32).to_le_bytes();
        
        out.extend_from_slice(&datalen);

        out.extend(data);

        code += &format!("    {name} = {i},\n");
    }

    code += "}";
    
    fs::write(format!("game/src/gen_{file_name}.rs"), &code).expect("failed to save rs file");
    fs::write(format!("smq_proj/build/{file_name}.ssf"), &out).expect("failed to save asf file");
}

pub fn load_ssf(data: Vec<u8>) -> Result<Vec<SSFAsset>, Error> {
    let mut out = Vec::new();

    if data.len() < 3 || &data[0..3] != b"SSF" {
        return Err(Error::new(ErrorKind::InvalidData, "file not SSF file"));
    }

    let mut pointer: usize = 3;

    while pointer < data.len() {
        let type_ = data[pointer];
        pointer += 1;

        if pointer + 4 > data.len() {
            return Err(Error::new(ErrorKind::UnexpectedEof, "unexpected end of file reading size"));
        }

        let size_arr: [u8; 4] = data[pointer..(pointer + 4)].try_into().unwrap();
        let size = u32::from_le_bytes(size_arr) as usize;
        pointer += 4;

        if pointer + size > data.len() {
            return Err(Error::new(ErrorKind::UnexpectedEof, "unexpected end of file reading data"));
        }

        let partdata = data[pointer..(pointer + size)].to_vec();
        pointer += size;

        match type_ {
            0x00 => out.push(SSFAsset::Binary(partdata)),
            _ => return Err(Error::new(ErrorKind::InvalidData, format!("unknown type: {type_}"))),
        }
    }
    
    return Ok(out);
}